# Generated by Django 6.0.7 on 2026-09-21 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('LAPTOP', 'Laptop / Computer'), ('PHONE', 'Mobile Phone'), ('VEHICLE', 'Company Vehicle'), ('ID_CARD', 'Access / ID Card'), ('EQUIPMENT', 'Office Equipment')], default='LAPTOP', max_length=50)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('condition', models.CharField(default='New / Good', max_length=100)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_assets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
