# Generated by Django 6.0.7 on 2026-09-22 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_employeeprofile_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='job_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
