# Generated by Django 6.0.7 on 2026-09-22 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_migrate_employee_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='employment_status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('PROBATION', 'Probation'), ('ON_LEAVE', 'On Leave'), ('SUSPENDED', 'Suspended'), ('RESIGNED', 'Resigned'), ('TERMINATED', 'Terminated'), ('RETIRED', 'Retired'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='employment_type',
            field=models.CharField(choices=[('FULL_TIME', 'Full Time'), ('PART_TIME', 'Part Time'), ('CONTRACT', 'Contract'), ('TEMPORARY', 'Temporary'), ('INTERN', 'Intern')], default='FULL_TIME', max_length=20),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='location',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to='accounts.employeeprofile'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='employee_photos/'),
        ),
    ]
