# Generated by Django 6.0.7 on 2026-09-25 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_emergencycontact_employeecontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token_version',
            field=models.PositiveIntegerField(default=1, help_text='Security version used to invalidate previously issued JWT tokens.'),
        ),
    ]
