# Generated by Django 6.0.7 on 2026-09-26 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_failed_login_attempts_user_locked_until'),
        ('organization', '0004_reconcile_position_master_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='organization_location',
            field=models.ForeignKey(blank=True, help_text='Authoritative organization location for this employee.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='organization.location'),
        ),
    ]
