# Generated by Django 6.0.7 on 2026-09-27 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_mfachallenge'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(help_text='Identity provider identifier, e.g. microsoft_entra_id.', max_length=50)),
                ('issuer', models.URLField(help_text='OIDC issuer URL identifying the identity provider/tenant.', max_length=500)),
                ('subject', models.CharField(help_text='OIDC subject (sub) claim identifying the external account.', max_length=255)),
                ('email', models.EmailField(blank=True, help_text='Email supplied by the identity provider for reference only.', max_length=254)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_identities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['provider', 'issuer'], name='extid_provider_issuer_idx')],
                'constraints': [models.UniqueConstraint(fields=('issuer', 'subject'), name='unique_external_identity_issuer_subject')],
            },
        ),
    ]
