# Generated by Django 6.0.7 on 2026-09-22 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_modules', '0002_remove_expenseclaim_title_employeeprofile_position_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeProfile',
        ),
    ]
