# Generated by Django 6.0.7 on 2026-09-19 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenseclaim',
            name='approved_by',
        ),
        migrations.AlterField(
            model_name='expenseclaim',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='expenseclaim',
            name='claim_type',
            field=models.CharField(choices=[('MEDICAL', 'Medical Expenses'), ('TRANSPORT', 'Travel & Transport'), ('FUNERAL', 'Funeral & Welfare Support'), ('OTHER', 'Other Operational Expenses')], default='OTHER', max_length=20),
        ),
        migrations.AlterField(
            model_name='expenseclaim',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='expenseclaim',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='expenseclaim',
            name='status',
            field=models.CharField(default='PENDING', max_length=20),
        ),
    ]
