# Generated by Django 6.0.7 on 2026-09-26 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_company_costcenter_division_jobgrade_jobtitle_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments', to='organization.division'),
        ),
        migrations.AddField(
            model_name='position',
            name='cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positions', to='organization.costcenter'),
        ),
        migrations.AddField(
            model_name='position',
            name='job_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positions', to='organization.jobgrade'),
        ),
        migrations.AddField(
            model_name='position',
            name='job_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positions', to='organization.jobtitle'),
        ),
        migrations.AddField(
            model_name='position',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positions', to='organization.section'),
        ),
    ]
